// The Vachan curriculum: the same learning path for all six languages.
//
// CONCEPTS lists everything the course teaches (in English, with a topic). Each language file
// (languages/<code>.ts) says every concept the natural way in that language, so the path is the
// same everywhere but the words, word order and politeness are language-specific.
//
// CURRICULUM groups the concepts into units and lessons, from the script to everyday
// conversations. Script units (letters) are generated from Unicode in script.ts.
import type { LearningStage, LessonKind } from "../../src/generated/prisma/client.ts";

/** Vocabulary topics (VocabularyItem.topic). The role-play scenarios refer to some of these. */
export const TOPICS = {
  greetings: "Greetings",
  polite: "Polite words",
  things: "Everyday things",
  actions: "Actions",
  questions: "Questions",
  intro: "Introductions",
  understanding: "Understanding",
  family: "Family",
  people: "People",
  describing: "Describing people",
  food: "Food",
  drinks: "Drinks",
  fruitsVeg: "Fruits & vegetables",
  restaurant: "Restaurant",
  numbers: "Numbers",
  time: "Time",
  days: "Days",
  routine: "Daily routine",
  activities: "Activities",
  places: "Places",
  directions: "Directions",
  shopping: "Shopping",
  colours: "Colours",
  clothes: "Clothes",
  transport: "Transport",
  travel: "Travel",
  conversation: "Conversation",
  pronouns: "Pronouns",
  grammar: "Grammar",
  feelings: "Feelings",
  body: "Body",
  health: "Health",
  relationships: "Relationships",
  weather: "Weather",
  college: "College & work",
  hobbies: "Hobbies",
  plans: "Plans & invitations",
  help: "Requests & help",
} as const;

const T = TOPICS;

export type ConceptDef = {
  /** English meaning. "(city)"-style placeholders must be filled in by each language's `meaning`. */
  en: string;
  topic: string;
  kind: "WORD" | "PHRASE";
  /** Extra English answers accepted for every language. */
  accept?: string[];
  /** True when the English depends on the language (e.g. a local city or the language's name). */
  localized?: boolean;
};

const w = (en: string, topic: string, accept?: string[]): ConceptDef => ({
  en,
  topic,
  kind: "WORD",
  accept,
});
const p = (en: string, topic: string, accept?: string[]): ConceptDef => ({
  en,
  topic,
  kind: "PHRASE",
  accept,
});
/** A phrase whose English must be localized by each language (e.g. "I live in Chennai."). */
const pl = (en: string, topic: string): ConceptDef => ({
  en,
  topic,
  kind: "PHRASE",
  localized: true,
});

export const CONCEPTS = {
  // Unit 4 — First words
  hello: w("Hello", T.greetings, ["hi", "namaste"]),
  goodbye: w("Goodbye", T.greetings, ["bye"]),
  seeYouLater: p("See you later.", T.greetings, ["see you", "bye for now"]),
  goodMorning: p("Good morning.", T.greetings),
  goodNight: p("Good night.", T.greetings),
  thankYou: w("Thank you", T.greetings, ["thanks"]),
  welcome: w("Welcome", T.greetings),
  yes: w("Yes", T.polite),
  no: w("No", T.polite),
  please: w("Please", T.polite),
  sorry: w("Sorry", T.polite, ["i am sorry", "i'm sorry"]),
  excuseMe: p("Excuse me.", T.polite),
  okay: w("Okay", T.polite, ["ok", "alright", "fine"]),
  noProblem: p("No problem.", T.polite, ["it's no problem", "never mind"]),
  youreWelcome: p("You're welcome.", T.polite, ["you are welcome", "it's nothing"]),
  water: w("Water", T.things),
  food: w("Food", T.things, ["meal"]),
  house: w("House", T.things, ["home"]),
  book: w("Book", T.things),
  phone: w("Phone", T.things, ["mobile", "mobile phone"]),
  bag: w("Bag", T.things),
  pen: w("Pen", T.things),
  money: w("Money", T.things),
  come: w("To come", T.actions, ["come"]),
  go: w("To go", T.actions, ["go"]),
  eat: w("To eat", T.actions, ["eat"]),
  drink: w("To drink", T.actions, ["drink"]),
  see: w("To see", T.actions, ["see", "look"]),
  give: w("To give", T.actions, ["give"]),
  take: w("To take", T.actions, ["take"]),
  doVerb: w("To do", T.actions, ["do"]),
  this: w("This", T.questions),
  that: w("That", T.questions),
  here: w("Here", T.directions),
  there: w("There", T.directions),
  what: w("What", T.questions),
  who: w("Who", T.questions),
  whatIsThis: p("What is this?", T.questions, ["what's this"]),
  whoIsThis: p("Who is this?", T.questions, ["who's this"]),
  thisIsWater: p("This is water.", T.questions),

  // Unit 5 — Introducing yourself
  name: w("Name", T.intro),
  iPronoun: w("I", T.pronouns),
  youFormal: w("You (polite)", T.pronouns, ["you"]),
  my: w("My", T.pronouns),
  yourFormal: w("Your (polite)", T.pronouns, ["your"]),
  myNameIs: p("My name is Asha.", T.intro, ["i am asha", "i'm asha"]),
  whatIsYourName: p("What is your name?", T.intro, ["what's your name"]),
  howAreYou: p("How are you?", T.intro),
  iAmFine: p("I am fine.", T.intro, ["i am well", "i'm good", "i am good"]),
  andYou: p("And you?", T.intro, ["what about you"]),
  veryGood: p("Very good.", T.intro, ["very well", "very nice"]),
  iAmAlsoFine: p("I am also fine.", T.intro, ["i am fine too", "i'm fine too"]),
  whereAreYouFrom: p("Where are you from?", T.intro),
  iAmFromIndia: p("I am from India.", T.intro, ["i come from india"]),
  india: w("India", T.intro),
  city: w("City", T.intro, ["town"]),
  village: w("Village", T.intro),
  country: w("Country", T.intro),
  whereDoYouLive: p("Where do you live?", T.intro),
  iLiveInCity: pl("I live in (a city of the region).", T.intro),
  niceToMeetYou: p("Nice to meet you.", T.intro, ["pleased to meet you", "glad to meet you"]),
  iAmAStudent: p("I am a student.", T.intro),
  iAmLearningLanguage: pl("I am learning (this language).", T.intro),
  iSpeakALittle: pl("I speak a little (this language).", T.intro),
  student: w("Student", T.college),
  teacher: w("Teacher", T.college),
  iUnderstand: p("I understand.", T.understanding),
  iDontUnderstand: p("I don't understand.", T.understanding, ["i do not understand"]),
  pleaseRepeat: p("Please say it again.", T.understanding, [
    "please repeat",
    "say that again please",
  ]),
  speakSlowly: p("Please speak slowly.", T.understanding, ["slowly please", "speak slowly please"]),
  whatDoesThisMean: p("What does this mean?", T.understanding),
  doYouSpeakEnglish: p("Do you speak English?", T.understanding, ["can you speak english"]),
  howDoYouSay: pl("How do you say this in (this language)?", T.understanding),

  // Unit 6 — Family & people
  mother: w("Mother", T.family, ["mom", "mum"]),
  father: w("Father", T.family, ["dad"]),
  parents: w("Parents", T.family),
  son: w("Son", T.family),
  daughter: w("Daughter", T.family),
  child: w("Child", T.family, ["kid"]),
  family: w("Family", T.family),
  elderBrother: w("Elder brother", T.family, ["older brother", "big brother"]),
  youngerBrother: w("Younger brother", T.family, ["little brother"]),
  elderSister: w("Elder sister", T.family, ["older sister", "big sister"]),
  youngerSister: w("Younger sister", T.family, ["little sister"]),
  husband: w("Husband", T.family),
  wife: w("Wife", T.family),
  grandfatherPaternal: w("Grandfather (father's father)", T.family, ["grandfather"]),
  grandmotherPaternal: w("Grandmother (father's mother)", T.family, ["grandmother"]),
  grandfatherMaternal: w("Grandfather (mother's father)", T.family, ["grandfather"]),
  grandmotherMaternal: w("Grandmother (mother's mother)", T.family, ["grandmother"]),
  uncleMaternal: w("Uncle (mother's brother)", T.family, ["uncle"]),
  auntPaternal: w("Aunt (father's sister)", T.family, ["aunt"]),
  man: w("Man", T.people),
  woman: w("Woman", T.people),
  boy: w("Boy", T.people),
  girl: w("Girl", T.people),
  friend: w("Friend", T.people),
  neighbour: w("Neighbour", T.people, ["neighbor"]),
  person: w("Person", T.people),
  doctor: w("Doctor", T.people),
  tall: w("Tall", T.describing),
  short: w("Short (height)", T.describing, ["short"]),
  good: w("Good", T.describing, ["nice"]),
  beautiful: w("Beautiful", T.describing, ["pretty"]),
  young: w("Young", T.describing),
  old: w("Old (age)", T.describing, ["old", "elderly"]),
  kind: w("Kind", T.describing, ["kind-hearted"]),
  thisIsMyMother: p("This is my mother.", T.family),
  heIsMyFriend: p("He is my friend.", T.people),
  sheIsMySister: p("She is my elder sister.", T.family, [
    "she is my sister",
    "she is my older sister",
  ]),
  myFatherIsADoctor: p("My father is a doctor.", T.family),
  howManyBrothers: p("How many brothers do you have?", T.family),
  iHaveOneBrother: p("I have one younger brother.", T.family, ["i have a younger brother"]),
  iHaveTwoSisters: p("I have two sisters.", T.family),

  // Unit 7 — Food & drinks
  rice: w("Rice", T.food),
  roti: w("Roti (flatbread)", T.food, ["roti", "chapati", "bread"]),
  dal: w("Dal (lentils)", T.food, ["dal", "lentils"]),
  vegetables: w("Vegetables", T.food),
  curd: w("Curd (yogurt)", T.food, ["curd", "yogurt"]),
  salt: w("Salt", T.food),
  sugar: w("Sugar", T.food),
  sweets: w("Sweets", T.food, ["sweet", "dessert"]),
  tea: w("Tea", T.drinks, ["chai"]),
  coffee: w("Coffee", T.drinks),
  milk: w("Milk", T.drinks),
  juice: w("Juice", T.drinks),
  buttermilk: w("Buttermilk", T.drinks),
  coconutWater: w("Coconut water", T.drinks),
  fruit: w("Fruit", T.fruitsVeg),
  banana: w("Banana", T.fruitsVeg),
  mango: w("Mango", T.fruitsVeg),
  apple: w("Apple", T.fruitsVeg),
  onion: w("Onion", T.fruitsVeg),
  tomato: w("Tomato", T.fruitsVeg),
  potato: w("Potato", T.fruitsVeg),
  egg: w("Egg", T.food),
  fish: w("Fish", T.food),
  chicken: w("Chicken", T.food),
  hungry: w("Hungry", T.food),
  thirsty: w("Thirsty", T.drinks),
  tasty: w("Tasty", T.food, ["delicious"]),
  spicy: w("Spicy", T.food, ["hot"]),
  sweetTaste: w("Sweet (taste)", T.food, ["sweet"]),
  iAmHungry: p("I am hungry.", T.food, ["i'm hungry"]),
  iAmThirsty: p("I am thirsty.", T.drinks, ["i'm thirsty"]),
  iWantWater: p("I want water.", T.drinks, ["i need water", "i want some water"]),
  iWantTea: p("I want tea.", T.drinks, ["i would like tea"]),
  iWantFood: p("I want food.", T.food, ["i need food", "i want a meal"]),
  iDontEatMeat: p("I don't eat meat.", T.food, ["i do not eat meat"]),
  giveMeOneTea: p("Please give me one tea.", T.restaurant, ["one tea please", "give me one tea"]),
  whatWouldYouLike: p("What would you like?", T.restaurant, ["what do you want"]),
  billPlease: p("The bill, please.", T.restaurant, ["bill please", "can i have the bill"]),
  withoutSugar: p("Without sugar, please.", T.restaurant, ["no sugar please"]),
  isItSpicy: p("Is it spicy?", T.restaurant),
  itIsVeryTasty: p("It is very tasty.", T.restaurant, ["it's very tasty", "it is delicious"]),
  giveMeWater: p("Please give me some water.", T.restaurant, [
    "give me water please",
    "water please",
  ]),
  oneMorePlease: p("One more, please.", T.restaurant, ["one more please"]),
  breakfast: w("Breakfast", T.food),
  lunch: w("Lunch", T.food),
  dinner: w("Dinner", T.food),

  // Unit 8 — Numbers, time & dates
  one: w("One", T.numbers, ["1"]),
  two: w("Two", T.numbers, ["2"]),
  three: w("Three", T.numbers, ["3"]),
  four: w("Four", T.numbers, ["4"]),
  five: w("Five", T.numbers, ["5"]),
  six: w("Six", T.numbers, ["6"]),
  seven: w("Seven", T.numbers, ["7"]),
  eight: w("Eight", T.numbers, ["8"]),
  nine: w("Nine", T.numbers, ["9"]),
  ten: w("Ten", T.numbers, ["10"]),
  eleven: w("Eleven", T.numbers, ["11"]),
  twelve: w("Twelve", T.numbers, ["12"]),
  thirteen: w("Thirteen", T.numbers, ["13"]),
  fourteen: w("Fourteen", T.numbers, ["14"]),
  fifteen: w("Fifteen", T.numbers, ["15"]),
  sixteen: w("Sixteen", T.numbers, ["16"]),
  seventeen: w("Seventeen", T.numbers, ["17"]),
  eighteen: w("Eighteen", T.numbers, ["18"]),
  nineteen: w("Nineteen", T.numbers, ["19"]),
  twenty: w("Twenty", T.numbers, ["20"]),
  thirty: w("Thirty", T.numbers, ["30"]),
  forty: w("Forty", T.numbers, ["40"]),
  fifty: w("Fifty", T.numbers, ["50"]),
  hundred: w("Hundred", T.numbers, ["100", "one hundred"]),
  thousand: w("Thousand", T.numbers, ["1000", "one thousand"]),
  howMany: p("How many?", T.numbers),
  age: w("Age", T.numbers),
  year: w("Year", T.time),
  howOldAreYou: p("How old are you?", T.numbers),
  iAmTwentyYearsOld: p("I am twenty years old.", T.numbers, ["i'm twenty", "i am twenty"]),
  phoneNumber: w("Phone number", T.numbers),
  whatIsYourPhoneNumber: p("What is your phone number?", T.numbers, ["what's your phone number"]),
  time: w("Time", T.time),
  now: w("Now", T.time),
  today: w("Today", T.time),
  tomorrow: w("Tomorrow", T.time),
  yesterday: w("Yesterday", T.time),
  morning: w("Morning", T.time),
  afternoon: w("Afternoon", T.time),
  evening: w("Evening", T.time),
  night: w("Night", T.time),
  whatTimeIsIt: p("What time is it?", T.time, ["what's the time"]),
  itIsFiveOClock: p("It is five o'clock.", T.time, ["it's five o'clock", "it is five"]),
  monday: w("Monday", T.days),
  tuesday: w("Tuesday", T.days),
  wednesday: w("Wednesday", T.days),
  thursday: w("Thursday", T.days),
  friday: w("Friday", T.days),
  saturday: w("Saturday", T.days),
  sunday: w("Sunday", T.days),
  day: w("Day", T.days),
  week: w("Week", T.days),
  month: w("Month", T.days),
  whatDayIsToday: p("What day is it today?", T.days, ["what day is today"]),
  todayIsMonday: p("Today is Monday.", T.days),

  // Unit 9 — Daily life
  wakeUp: w("To wake up", T.routine, ["wake up", "get up"]),
  sleep: w("To sleep", T.routine, ["sleep"]),
  bathe: w("To bathe", T.routine, ["bathe", "take a bath", "shower"]),
  cook: w("To cook", T.routine, ["cook"]),
  wash: w("To wash", T.routine, ["wash"]),
  wear: w("To wear", T.routine, ["wear", "put on"]),
  study: w("To study", T.activities, ["study"]),
  work: w("To work", T.activities, ["work"]),
  read: w("To read", T.activities, ["read"]),
  write: w("To write", T.activities, ["write"]),
  play: w("To play", T.activities, ["play"]),
  listen: w("To listen", T.activities, ["listen", "hear"]),
  speak: w("To speak", T.activities, ["speak", "talk"]),
  sit: w("To sit", T.activities, ["sit"]),
  stand: w("To stand", T.activities, ["stand"]),
  walk: w("To walk", T.activities, ["walk"]),
  run: w("To run", T.activities, ["run"]),
  wait: w("To wait", T.activities, ["wait"]),
  open: w("To open", T.activities, ["open"]),
  close: w("To close", T.activities, ["close", "shut"]),
  whatAreYouDoing: p("What are you doing?", T.routine),
  iAmStudying: p("I am studying.", T.routine, ["i'm studying"]),
  iAmEating: p("I am eating.", T.routine, ["i'm eating"]),
  iAmDrinkingWater: p("I am drinking water.", T.routine, ["i'm drinking water"]),
  iAmSleeping: p("I am sleeping.", T.routine, ["i'm sleeping"]),
  iAmWorking: p("I am working.", T.routine, ["i'm working"]),
  iAmComing: p("I am coming.", T.routine, ["i'm coming", "coming"]),
  iAmGoing: p("I am going.", T.routine, ["i'm going", "i'm leaving"]),
  iAmGoingHome: p("I am going home.", T.routine, ["i'm going home"]),
  iAmGoingToCollege: p("I am going to college.", T.routine, ["i'm going to college"]),
  everyDay: w("Every day", T.routine, ["daily"]),
  iWakeUpAtSix: p("I wake up at six o'clock.", T.routine, ["i get up at six", "i wake up at six"]),
  iGoToCollegeEveryDay: p("I go to college every day.", T.routine),
  iEatLunchAtOne: p("I eat lunch at one o'clock.", T.routine, ["i have lunch at one"]),
  iSleepAtTen: p("I sleep at ten o'clock at night.", T.routine, [
    "i sleep at ten",
    "i go to bed at ten",
  ]),

  // Unit 10 — Places & directions
  school: w("School", T.places),
  college: w("College", T.places),
  office: w("Office", T.places),
  shop: w("Shop", T.places, ["store"]),
  market: w("Market", T.places),
  restaurant: w("Restaurant", T.places, ["hotel"]),
  hospital: w("Hospital", T.places),
  station: w("Railway station", T.places, ["station"]),
  bank: w("Bank", T.places),
  temple: w("Temple", T.places),
  bathroom: w("Bathroom", T.places, ["toilet", "washroom"]),
  road: w("Road", T.places, ["street"]),
  near: w("Near", T.directions, ["close"]),
  far: w("Far", T.directions),
  left: w("Left", T.directions),
  right: w("Right", T.directions),
  straight: w("Straight", T.directions, ["straight ahead"]),
  inFront: w("In front", T.directions, ["in front of", "ahead"]),
  behind: w("Behind", T.directions),
  inside: w("Inside", T.directions),
  outside: w("Outside", T.directions),
  where: w("Where", T.questions),
  whereIsTheBathroom: p("Where is the bathroom?", T.directions, [
    "where is the toilet",
    "where is the washroom",
  ]),
  whereIsTheStation: p("Where is the railway station?", T.directions, ["where is the station"]),
  goStraight: p("Go straight.", T.directions, ["go straight ahead"]),
  turnLeft: p("Turn left.", T.directions, ["go left"]),
  turnRight: p("Turn right.", T.directions, ["go right"]),
  itIsNear: p("It is near.", T.directions, ["it's near", "it is close"]),
  itIsFar: p("It is far.", T.directions, ["it's far"]),
  howFarIsIt: p("How far is it?", T.directions),
  whereAreYouGoing: p("Where are you going?", T.directions),
  iAmGoingToTheMarket: p("I am going to the market.", T.directions, ["i'm going to the market"]),
  whereAreYou: p("Where are you?", T.directions),
  iAmAtHome: p("I am at home.", T.directions, ["i'm at home"]),
  comeHere: p("Come here.", T.directions, ["please come here"]),
  waitHere: p("Please wait here.", T.directions, ["wait here"]),

  // Unit 11 — Shopping & money
  rupee: w("Rupee", T.shopping, ["rupees"]),
  price: w("Price", T.shopping, ["cost"]),
  buy: w("To buy", T.shopping, ["buy"]),
  sell: w("To sell", T.shopping, ["sell"]),
  expensive: w("Expensive", T.shopping, ["costly"]),
  cheap: w("Cheap", T.shopping, ["inexpensive"]),
  howMuch: w("How much", T.shopping, ["how much?"]),
  red: w("Red", T.colours),
  blue: w("Blue", T.colours),
  green: w("Green", T.colours),
  yellow: w("Yellow", T.colours),
  white: w("White", T.colours),
  black: w("Black", T.colours),
  colour: w("Colour", T.colours, ["color"]),
  clothes: w("Clothes", T.clothes),
  shirt: w("Shirt", T.clothes),
  trousers: w("Trousers", T.clothes, ["pants"]),
  saree: w("Saree", T.clothes, ["sari"]),
  shoes: w("Shoes", T.clothes),
  slippers: w("Slippers (chappals)", T.clothes, ["slippers", "sandals", "chappals"]),
  howMuchIsThis: p("How much does this cost?", T.shopping, [
    "how much is this",
    "what is the price of this",
  ]),
  thisIsTooExpensive: p("This is too expensive.", T.shopping, [
    "this is very expensive",
    "it's too expensive",
  ]),
  reduceThePrice: p("Please reduce the price a little.", T.shopping, [
    "please give a discount",
    "reduce the price please",
  ]),
  doYouHaveMangoes: p("Do you have mangoes?", T.shopping),
  iNeedABag: p("I need a bag.", T.shopping),
  giveMeThisOne: p("Please give me this one.", T.shopping, ["give me this one", "i want this one"]),
  iWillTakeIt: p("I will take it.", T.shopping, ["i'll take it", "i'll buy it"]),
  showMeThatOne: p("Please show me that one.", T.shopping, ["show me that one"]),
  doYouHaveARedOne: p("Do you have a red one?", T.shopping, ["do you have it in red"]),

  // Unit 12 — Travel & transport
  bus: w("Bus", T.transport),
  train: w("Train", T.transport),
  autoRickshaw: w("Auto-rickshaw", T.transport, ["auto", "rickshaw"]),
  taxi: w("Taxi", T.transport, ["cab"]),
  car: w("Car", T.transport),
  bike: w("Motorbike", T.transport, ["bike", "two-wheeler", "scooter"]),
  ticket: w("Ticket", T.travel),
  platform: w("Platform", T.travel),
  busStop: w("Bus stop", T.travel),
  airport: w("Airport", T.travel),
  luggage: w("Luggage", T.travel, ["bags"]),
  journey: w("Journey", T.travel, ["trip"]),
  when: w("When", T.questions),
  howLong: w("How long", T.questions),
  late: w("Late", T.time),
  early: w("Early", T.time),
  quickly: w("Quickly", T.travel, ["fast"]),
  slowly: w("Slowly", T.travel),
  whenDoesTheBusCome: p("When will the bus come?", T.travel, ["when does the bus come"]),
  howLongDoesItTake: p("How long will it take?", T.travel, ["how long does it take"]),
  theTrainIsLate: p("The train is late.", T.travel),
  oneTicketPlease: pl("One ticket to (a city of the region), please.", T.travel),
  whichPlatform: p("Which platform?", T.travel, ["which platform is it"]),
  stopHerePlease: p("Please stop here.", T.travel, ["stop here please", "stop here"]),
  goSlowlyPlease: p("Please go slowly.", T.travel, ["go slowly please", "drive slowly please"]),
  howMuchToStation: p("How much to the railway station?", T.travel, ["how much to the station"]),
  iAmLost: p("I am lost.", T.travel, ["i'm lost", "i have lost my way"]),
  doesThisBusGoToStation: p("Does this bus go to the railway station?", T.travel, [
    "does this bus go to the station",
  ]),

  // Unit 13 — Everyday conversations (key phrases; the dialogues are separate)
  whatsNew: p("What's new?", T.conversation, ["what is new", "what's up"]),
  longTimeNoSee: p("Long time no see.", T.conversation, ["it has been a long time"]),
  haveYouEaten: p("Have you eaten?", T.conversation, ["did you eat"]),
  yesIAte: p("Yes, I have eaten.", T.conversation, ["yes i ate", "yes i have eaten"]),
  whatIsTheNameOfThisPlace: p("What is this place called?", T.conversation),
  hello_onPhone: p("Answering the phone: Hello?", T.conversation, ["hello", "hello?"]),
  whoIsSpeaking: p("Who is speaking?", T.conversation, ["who is this"]),
  callYouLater: p("I will call you later.", T.conversation, ["i'll call you later"]),
  canYouHearMe: p("Can you hear me?", T.conversation),
  whereIsTheClass: p("Where is the classroom?", T.conversation, ["where is the class"]),
  whenIsTheExam: p("When is the exam?", T.conversation),
  canIComeIn: p("May I come in?", T.conversation, ["can i come in"]),
  justAMinute: p("Just a minute.", T.conversation, ["one minute", "wait a minute"]),
  ofCourse: p("Of course.", T.conversation, ["sure", "certainly"]),
  isThisSeatFree: p("Is this seat free?", T.conversation, ["is this seat empty", "can i sit here"]),

  // Unit 14 — Grammar & sentence building
  youCasual: w("You (casual)", T.pronouns, ["you"]),
  he: w("He", T.pronouns),
  she: w("She", T.pronouns),
  we: w("We", T.pronouns),
  they: w("They", T.pronouns),
  itPronoun: w("It", T.pronouns),
  iEatRice: p("I eat rice.", T.grammar),
  sheDrinksTea: p("She drinks tea.", T.grammar),
  weGoToCollege: p("We go to college.", T.grammar),
  heReadsABook: p("He reads a book.", T.grammar, ["he is reading a book"]),
  theyLiveInIndia: p("They live in India.", T.grammar),
  myMotherCooksFood: p("My mother cooks food.", T.grammar, ["my mother cooks"]),
  iSpeakEnglish: p("I speak English.", T.grammar, ["i can speak english"]),
  iAteRice: p("I ate rice.", T.grammar),
  iWillEatRice: p("I will eat rice.", T.grammar, ["i'll eat rice"]),
  iWentToTheMarketYesterday: p("I went to the market yesterday.", T.grammar, [
    "yesterday i went to the market",
  ]),
  iWillGoTomorrow: p("I will go tomorrow.", T.grammar, ["i'll go tomorrow", "tomorrow i will go"]),
  sheCameYesterday: p("She came yesterday.", T.grammar),
  weWillComeTomorrow: p("We will come tomorrow.", T.grammar, ["we'll come tomorrow"]),
  why: w("Why", T.questions),
  how: w("How", T.questions),
  which: w("Which", T.questions),
  doYouEatMeat: p("Do you eat meat?", T.grammar),
  iDontKnow: p("I don't know.", T.grammar, ["i do not know"]),
  isThisYourBook: p("Is this your book?", T.grammar),
  thisIsNotMyBook: p("This is not my book.", T.grammar, ["this isn't my book"]),
  whyAreYouLate: p("Why are you late?", T.grammar),
  howDoYouGoToCollege: p("How do you go to college?", T.grammar),
  inPostposition: w("In (inside)", T.grammar, ["in"]),
  onPostposition: w("On (on top of)", T.grammar, ["on"]),
  withPostposition: w("With", T.grammar),
  fromPostposition: w("From", T.grammar),
  table: w("Table", T.things),
  thisIsMyBook: p("This is my book.", T.grammar),
  hisNameIsRavi: p("His name is Ravi.", T.grammar),
  theBookIsOnTheTable: p("The book is on the table.", T.grammar),
  iGoWithMyFriend: p("I go with my friend.", T.grammar, ["i am going with my friend"]),
  sheIsComingFromHome: p("She is coming from home.", T.grammar),
  comeCasual: p("Come! (to a friend)", T.grammar, ["come"]),
  comePolite: p("Please come. (polite)", T.grammar, ["please come"]),
  sitCasual: p("Sit! (to a friend)", T.grammar, ["sit", "sit down"]),
  sitPolite: p("Please sit down. (polite)", T.grammar, ["please sit", "please have a seat"]),
  eatPolite: p("Please eat. (to a guest)", T.grammar, ["please eat", "please have some food"]),
  howAreYouCasual: p("How are you? (to a friend)", T.grammar, ["how are you"]),

  // Unit 15 — Feelings, health & relationships
  happy: w("Happy", T.feelings, ["glad"]),
  sad: w("Sad", T.feelings),
  angry: w("Angry", T.feelings),
  tired: w("Tired", T.feelings),
  scared: w("Scared", T.feelings, ["afraid", "frightened"]),
  worried: w("Worried", T.feelings),
  iAmHappy: p("I am happy.", T.feelings, ["i'm happy"]),
  iAmSad: p("I am sad.", T.feelings, ["i'm sad"]),
  iAmTired: p("I am tired.", T.feelings, ["i'm tired"]),
  iAmAngry: p("I am angry.", T.feelings, ["i'm angry"]),
  iAmOkay: p("I am okay.", T.feelings, ["i'm okay", "i am alright", "i'm ok"]),
  iAmNotFeelingWell: p("I am not feeling well.", T.health, [
    "i don't feel well",
    "i'm not well",
    "i am unwell",
  ]),
  dontWorry: p("Don't worry.", T.feelings, ["do not worry"]),
  iAmScared: p("I am scared.", T.feelings, ["i'm scared", "i am afraid"]),
  head: w("Head", T.body),
  hand: w("Hand", T.body),
  leg: w("Leg", T.body, ["foot"]),
  eye: w("Eye", T.body),
  ear: w("Ear", T.body),
  mouth: w("Mouth", T.body),
  stomach: w("Stomach", T.body, ["belly", "tummy"]),
  tooth: w("Tooth", T.body, ["teeth"]),
  fever: w("Fever", T.health),
  medicine: w("Medicine", T.health, ["tablet", "medicines"]),
  iHaveAFever: p("I have a fever.", T.health),
  iHaveAHeadache: p("I have a headache.", T.health, ["my head hurts"]),
  myStomachHurts: p("My stomach hurts.", T.health, ["i have a stomach ache"]),
  iNeedADoctor: p("I need a doctor.", T.health),
  callADoctor: p("Please call a doctor.", T.health, ["call a doctor"]),
  takeThisMedicine: p("Take this medicine.", T.health),
  iLoveYou: p("I love you.", T.relationships),
  iLikeYou: p("I like you.", T.relationships),
  iMissYou: p("I miss you.", T.relationships),
  iLoveMyFamily: p("I love my family.", T.relationships),
  youAreMyFriend: p("You are my friend.", T.relationships, ["you're my friend"]),
  youAreMyBestFriend: p("You are my best friend.", T.relationships, ["you're my best friend"]),
  iLikeThis: p("I like this.", T.relationships),
  iDontLikeThis: p("I don't like this.", T.relationships, ["i do not like this"]),
  takeCare: p("Take care.", T.relationships, ["take care of yourself"]),

  // Unit 16 — Practical communication
  weather: w("Weather", T.weather),
  hot: w("Hot", T.weather),
  cold: w("Cold", T.weather),
  rain: w("Rain", T.weather),
  sun: w("Sun", T.weather),
  wind: w("Wind", T.weather),
  itIsHotToday: p("It is hot today.", T.weather, ["it's hot today", "today is hot"]),
  itIsRaining: p("It is raining.", T.weather, ["it's raining"]),
  itIsColdToday: p("It is cold today.", T.weather, ["it's cold today"]),
  classroom: w("Class", T.college, ["classroom", "lecture"]),
  exam: w("Exam", T.college, ["examination", "test"]),
  homework: w("Homework", T.college),
  job: w("Job", T.college, ["work"]),
  holiday: w("Holiday", T.college, ["leave", "vacation"]),
  iHaveAnExamTomorrow: p("I have an exam tomorrow.", T.college),
  todayIsAHoliday: p("Today is a holiday.", T.college),
  iWorkInAnOffice: p("I work in an office.", T.college),
  music: w("Music", T.hobbies),
  movie: w("Movie", T.hobbies, ["film", "cinema"]),
  song: w("Song", T.hobbies),
  cricket: w("Cricket", T.hobbies),
  dance: w("Dance", T.hobbies),
  iLikeMusic: p("I like music.", T.hobbies),
  doYouLikeCricket: p("Do you like cricket?", T.hobbies),
  iLikeWatchingMovies: p("I like watching movies.", T.hobbies, [
    "i like movies",
    "i love watching movies",
  ]),
  whatIsYourHobby: p("What is your hobby?", T.hobbies, ["what are your hobbies"]),
  letsGo: p("Let's go.", T.plans, ["let us go", "come on, let's go"]),
  comeToMyHouse: p("Come to my house.", T.plans, ["please come to my house", "come home"]),
  areYouFreeTomorrow: p("Are you free tomorrow?", T.plans),
  yesIWillCome: p("Yes, I will come.", T.plans, ["yes i'll come", "i will come"]),
  sorryICantCome: p("Sorry, I can't come.", T.plans, ["sorry i cannot come"]),
  seeYouTomorrow: p("See you tomorrow.", T.plans, ["see you tomorrow then"]),
  canYouHelpMe: p("Can you help me?", T.help, ["could you help me", "please help me"]),
  iNeedHelp: p("I need help.", T.help),
  pleaseHelpMe: p("Please help me.", T.help, ["help me please"]),
  pleaseWait: p("Please wait.", T.help, ["wait please"]),
  pleaseTellMe: p("Please tell me.", T.help, ["tell me please", "tell me"]),
  pleaseShowMe: p("Please show me.", T.help, ["show me please", "show me"]),
  callMe: p("Please call me.", T.help, ["call me"]),
  help: p("Help!", T.help, ["help"]),
  itsOkay: p("It's okay.", T.help, ["it is okay", "that's fine", "it's fine"]),
} as const satisfies Record<string, ConceptDef>;

export type ConceptKey = keyof typeof CONCEPTS;

/** Shared beginner dialogues (English); each language writes a natural version. */
export const DIALOGUES = {
  meetingSomeone: {
    title: "Meeting someone new",
    lines: [
      "A: Hello.",
      "B: Hello.",
      "A: What is your name?",
      "B: My name is Asha. What is your name?",
      "A: My name is Ravi. Where are you from?",
      "B: I am from (a city of the region). Nice to meet you.",
      "A: Nice to meet you too.",
    ],
  },
  meetingFriend: {
    title: "Meeting a friend",
    lines: [
      "A: Hi! How are you?",
      "B: I am fine. And you?",
      "A: I am also fine. Long time no see!",
      "B: Yes. What are you doing these days?",
      "A: I am studying. Have you eaten?",
      "B: Yes, I have eaten. Let's have tea.",
      "A: Okay, let's go.",
    ],
  },
  restaurant: {
    title: "Ordering food",
    lines: [
      "A (waiter): What would you like?",
      "B: Please give me one plate of rice and dal.",
      "A: Anything to drink?",
      "B: One tea, without sugar, please.",
      "A: Okay. Anything else?",
      "B: Some water, please. Is it spicy?",
      "A: A little spicy.",
      "B: That's fine. The bill, please, after the meal.",
    ],
  },
  shopping: {
    title: "At the shop",
    lines: [
      "A: Do you have mangoes?",
      "B (shopkeeper): Yes, we have.",
      "A: How much does one kilo cost?",
      "B: One hundred rupees.",
      "A: That is too expensive. Please reduce the price a little.",
      "B: Okay, ninety rupees.",
      "A: Fine, I will take one kilo.",
    ],
  },
  directions: {
    title: "Asking for directions",
    lines: [
      "A: Excuse me, where is the railway station?",
      "B: Go straight, then turn left.",
      "A: Is it far?",
      "B: No, it is near. About five minutes on foot.",
      "A: Thank you very much.",
      "B: You're welcome.",
    ],
  },
  college: {
    title: "At college",
    lines: [
      "A: Hi, are you new here?",
      "B: Yes, today is my first day.",
      "A: Which class are you in?",
      "B: I am in first year. Where is the library?",
      "A: It is behind the office. Come, I will show you.",
      "B: Thank you! When is the exam?",
      "A: Next month.",
    ],
  },
  phoneCall: {
    title: "On the phone",
    lines: [
      "A: Hello?",
      "B: Hello, who is speaking?",
      "A: It's me, Ravi. Where are you?",
      "B: I am at home. What happened?",
      "A: Are you free tomorrow?",
      "B: Yes, I am free.",
      "A: Then come to my house in the evening.",
      "B: Okay, I will come. I will call you later.",
    ],
  },
  askingForHelp: {
    title: "Asking for help",
    lines: [
      "A: Excuse me, can you help me?",
      "B: Yes, tell me.",
      "A: I am lost. I don't understand this address.",
      "B: Show me. This is near the market.",
      "A: Please speak slowly.",
      "B: Go to the market and ask there. It is close.",
      "A: Thank you so much.",
    ],
  },
  travel: {
    title: "Taking a bus",
    lines: [
      "A: Does this bus go to the railway station?",
      "B (conductor): Yes. Where do you want to get off?",
      "A: At the railway station. How much is the ticket?",
      "B: Twenty rupees.",
      "A: How long will it take?",
      "B: About half an hour.",
      "A: Please tell me when we reach the station.",
      "B: Okay, I will tell you.",
    ],
  },
  dailyRoutine: {
    title: "Talking about your day",
    lines: [
      "A: What time do you wake up?",
      "B: I wake up at six o'clock.",
      "A: What do you do after that?",
      "B: I bathe, eat breakfast and go to college.",
      "A: When do you come home?",
      "B: I come home in the evening and study.",
      "A: When do you sleep?",
      "B: I sleep at ten o'clock at night.",
    ],
  },
} as const;

export type DialogueKey = keyof typeof DIALOGUES;

// Units and lessons

export type ScriptLessonKind = "vowels" | "consonants" | "signs" | "reading" | "script-review";

export type LessonPlan = {
  /** Stable key, used in lesson notes and extras. */
  key: string;
  title: string;
  intro: string;
  kind: LessonKind;
  /** New words/phrases taught in this lesson. */
  items?: ConceptKey[];
  /** Words from earlier lessons practised again (reviews, distractors). */
  practice?: ConceptKey[];
  /** [what someone says, a good reply] — "pick the right reply" exercises. */
  replies?: Array<[ConceptKey, ConceptKey]>;
  dialogue?: DialogueKey;
  /** Script lessons: which part of script.ts to use (1-based group number). */
  script?: { kind: ScriptLessonKind; group?: number };
};

export type UnitPlan = {
  key: string;
  title: string;
  description: string;
  stage: LearningStage;
  lessons: LessonPlan[];
};

const lesson = (
  key: string,
  title: string,
  kind: LessonKind,
  intro: string,
  items: ConceptKey[],
  extra: Partial<LessonPlan> = {},
): LessonPlan => ({ key, title, kind, intro, items, ...extra });

const scriptLesson = (
  key: string,
  title: string,
  intro: string,
  script: LessonPlan["script"],
  kind: LessonKind = "SCRIPT",
): LessonPlan => ({ key, title, kind, intro, script });

export const CURRICULUM: UnitPlan[] = [
  {
    key: "vowels",
    title: "Vowels",
    description: "Read and pronounce the vowels of the script, short and long.",
    stage: "FOUNDATIONS",
    lessons: [
      scriptLesson(
        "vowels-1",
        "Vowels 1",
        "Your first vowels. A short vowel and its long partner.",
        { kind: "vowels", group: 1 },
      ),
      scriptLesson(
        "vowels-2",
        "Vowels 2",
        "Another short/long pair. Hold the long one about twice as long.",
        { kind: "vowels", group: 2 },
      ),
      scriptLesson("vowels-3", "Vowels 3", "One more short/long pair.", {
        kind: "vowels",
        group: 3,
      }),
      scriptLesson("vowels-4", "Vowels 4", "The e-sounds and the ai-sound.", {
        kind: "vowels",
        group: 4,
      }),
      scriptLesson("vowels-5", "Vowels 5", "The o-sounds and the au-sound.", {
        kind: "vowels",
        group: 5,
      }),
      scriptLesson(
        "vowels-review",
        "Vowel review",
        "Check that you can read and hear every vowel.",
        { kind: "vowels" },
        "CHECKPOINT",
      ),
    ],
  },
  {
    key: "consonants",
    title: "Consonants",
    description: "Learn the consonants group by group. Each one carries a built-in vowel.",
    stage: "FOUNDATIONS",
    lessons: [1, 2, 3, 4, 5, 6].map((group) =>
      scriptLesson(`consonants-${group}`, `Consonants ${group}`, "", { kind: "consonants", group }),
    ),
  },
  {
    key: "reading",
    title: "Vowel signs & reading",
    description: "Combine consonants with vowel signs and read your first words.",
    stage: "FOUNDATIONS",
    lessons: [
      scriptLesson(
        "signs-1",
        "Vowel signs 1",
        "A consonant changes its vowel with a small mark called a vowel sign.",
        { kind: "signs", group: 1 },
      ),
      scriptLesson("signs-2", "Vowel signs 2", "More vowel signs: the u-sounds.", {
        kind: "signs",
        group: 2,
      }),
      scriptLesson("signs-3", "Vowel signs 3", "The e, ai, o and au signs.", {
        kind: "signs",
        group: 3,
      }),
      scriptLesson(
        "reading-words",
        "Reading words",
        "Put letters and signs together to read real words.",
        { kind: "reading" },
      ),
      scriptLesson(
        "script-review",
        "Script review",
        "Letters, signs and words — everything from the first three units.",
        { kind: "script-review" },
        "CHECKPOINT",
      ),
    ],
  },
  {
    key: "first-words",
    title: "First words",
    description: "Greetings, polite words, everyday things and simple actions.",
    stage: "FIRST_WORDS",
    lessons: [
      lesson(
        "greetings",
        "Greetings",
        "VOCABULARY",
        "Words you will use every day when you meet and leave people.",
        ["hello", "goodbye", "seeYouLater", "goodMorning", "goodNight", "thankYou", "welcome"],
        {
          replies: [
            ["hello", "hello"],
            ["goodMorning", "goodMorning"],
          ],
        },
      ),
      lesson(
        "polite-words",
        "Yes, no & polite words",
        "VOCABULARY",
        "Small words that make you sound friendly and polite.",
        ["yes", "no", "please", "sorry", "excuseMe", "okay", "noProblem", "youreWelcome"],
        {
          practice: ["thankYou"],
          replies: [
            ["sorry", "noProblem"],
            ["thankYou", "youreWelcome"],
          ],
        },
      ),
      lesson("things", "Everyday things", "VOCABULARY", "Things you see and use every day.", [
        "water",
        "food",
        "house",
        "book",
        "phone",
        "bag",
        "pen",
        "money",
      ]),
      lesson(
        "actions",
        "Common actions",
        "VOCABULARY",
        "Your first verbs. They are shown in their basic (dictionary) form.",
        ["come", "go", "eat", "drink", "see", "give", "take", "doVerb"],
      ),
      lesson(
        "this-and-that",
        "This, that & questions",
        "PHRASES",
        "Point at things and ask what they are.",
        ["this", "that", "here", "there", "what", "who", "whatIsThis", "whoIsThis", "thisIsWater"],
      ),
      lesson(
        "first-words-review",
        "First words review",
        "CHECKPOINT",
        "Greetings, polite words, things and actions together.",
        [],
        {
          practice: [
            "hello",
            "thankYou",
            "sorry",
            "please",
            "water",
            "book",
            "eat",
            "go",
            "whatIsThis",
          ],
        },
      ),
    ],
  },
  {
    key: "introductions",
    title: "Introducing yourself",
    description: "Say who you are, ask about others and handle not understanding.",
    stage: "EVERYDAY_PHRASES",
    lessons: [
      lesson(
        "my-name",
        "My name is…",
        "PHRASES",
        "Say your name and ask someone else's.",
        ["name", "iPronoun", "youFormal", "my", "yourFormal", "myNameIs", "whatIsYourName"],
        { replies: [["whatIsYourName", "myNameIs"]] },
      ),
      lesson(
        "how-are-you",
        "How are you?",
        "PHRASES",
        "Ask how someone is — and answer when they ask you.",
        ["howAreYou", "iAmFine", "andYou", "veryGood", "iAmAlsoFine"],
        {
          replies: [
            ["howAreYou", "iAmFine"],
            ["andYou", "iAmAlsoFine"],
          ],
        },
      ),
      lesson(
        "where-from",
        "Where are you from?",
        "PHRASES",
        "Talk about where you come from and where you live.",
        [
          "whereAreYouFrom",
          "iAmFromIndia",
          "india",
          "city",
          "village",
          "country",
          "whereDoYouLive",
          "iLiveInCity",
        ],
        {
          replies: [
            ["whereAreYouFrom", "iAmFromIndia"],
            ["whereDoYouLive", "iLiveInCity"],
          ],
        },
      ),
      lesson(
        "nice-to-meet-you",
        "Nice to meet you",
        "PHRASES",
        "Finish an introduction and say a little about yourself.",
        [
          "niceToMeetYou",
          "iAmAStudent",
          "iAmLearningLanguage",
          "iSpeakALittle",
          "student",
          "teacher",
        ],
        { replies: [["niceToMeetYou", "niceToMeetYou"]] },
      ),
      lesson(
        "understanding",
        "I don't understand",
        "PHRASES",
        "Phrases that keep a conversation going when you get lost.",
        [
          "iUnderstand",
          "iDontUnderstand",
          "pleaseRepeat",
          "speakSlowly",
          "whatDoesThisMean",
          "doYouSpeakEnglish",
          "howDoYouSay",
        ],
      ),
      lesson(
        "introductions-review",
        "Introductions review",
        "CHECKPOINT",
        "Introduce yourself from start to finish.",
        [],
        {
          practice: [
            "hello",
            "myNameIs",
            "whatIsYourName",
            "howAreYou",
            "iAmFine",
            "whereAreYouFrom",
            "niceToMeetYou",
            "iDontUnderstand",
            "iAmAStudent",
          ],
          replies: [
            ["howAreYou", "iAmFine"],
            ["whatIsYourName", "myNameIs"],
          ],
        },
      ),
    ],
  },
  {
    key: "family",
    title: "Family & people",
    description: "Family members, people around you and how to describe them.",
    stage: "FIRST_WORDS",
    lessons: [
      lesson(
        "parents-children",
        "Parents & children",
        "VOCABULARY",
        "The closest family members.",
        ["mother", "father", "parents", "son", "daughter", "child", "family"],
      ),
      lesson(
        "siblings",
        "Brothers, sisters & partners",
        "VOCABULARY",
        "Many Indian languages say whether a brother or sister is older or younger.",
        ["elderBrother", "youngerBrother", "elderSister", "youngerSister", "husband", "wife"],
      ),
      lesson(
        "grandparents",
        "Grandparents & relatives",
        "VOCABULARY",
        "Indian languages often have different words for the mother's and the father's side of the family.",
        [
          "grandfatherPaternal",
          "grandmotherPaternal",
          "grandfatherMaternal",
          "grandmotherMaternal",
          "uncleMaternal",
          "auntPaternal",
        ],
      ),
      lesson("people", "People", "VOCABULARY", "People you meet every day.", [
        "man",
        "woman",
        "boy",
        "girl",
        "friend",
        "neighbour",
        "person",
        "doctor",
      ]),
      lesson(
        "describing-people",
        "Describing people",
        "PHRASES",
        "Describe people and say who they are.",
        [
          "tall",
          "short",
          "good",
          "beautiful",
          "young",
          "old",
          "kind",
          "thisIsMyMother",
          "heIsMyFriend",
          "sheIsMySister",
          "myFatherIsADoctor",
        ],
      ),
      lesson(
        "family-review",
        "Family review",
        "CHECKPOINT",
        "Talk about your family.",
        ["howManyBrothers", "iHaveOneBrother", "iHaveTwoSisters"],
        {
          practice: [
            "mother",
            "father",
            "elderBrother",
            "youngerSister",
            "friend",
            "thisIsMyMother",
            "heIsMyFriend",
          ],
          replies: [["howManyBrothers", "iHaveOneBrother"]],
        },
      ),
    ],
  },
  {
    key: "food",
    title: "Food & drinks",
    description: "Everyday food, drinks, saying you are hungry and ordering a meal.",
    stage: "FIRST_WORDS",
    lessons: [
      lesson(
        "food-staples",
        "Everyday food",
        "VOCABULARY",
        "The food on an everyday Indian plate.",
        ["rice", "roti", "dal", "vegetables", "curd", "salt", "sugar", "sweets"],
        { practice: ["food"] },
      ),
      lesson(
        "drinks",
        "Drinks",
        "VOCABULARY",
        "Something to drink.",
        ["tea", "coffee", "milk", "juice", "buttermilk", "coconutWater"],
        { practice: ["water"] },
      ),
      lesson(
        "fruits-vegetables",
        "Fruits, vegetables & more",
        "VOCABULARY",
        "Fruit, vegetables, eggs, fish and chicken.",
        [
          "fruit",
          "banana",
          "mango",
          "apple",
          "onion",
          "tomato",
          "potato",
          "egg",
          "fish",
          "chicken",
        ],
      ),
      lesson(
        "hungry-thirsty",
        "Hungry & thirsty",
        "PHRASES",
        "Say how you feel and what you want.",
        [
          "hungry",
          "thirsty",
          "tasty",
          "spicy",
          "sweetTaste",
          "iAmHungry",
          "iAmThirsty",
          "iWantWater",
          "iWantTea",
          "iWantFood",
          "iDontEatMeat",
        ],
      ),
      lesson(
        "ordering-food",
        "Ordering food",
        "PHRASES",
        "Order at a restaurant or tea stall.",
        [
          "breakfast",
          "lunch",
          "dinner",
          "giveMeOneTea",
          "whatWouldYouLike",
          "billPlease",
          "withoutSugar",
          "isItSpicy",
          "itIsVeryTasty",
          "giveMeWater",
          "oneMorePlease",
        ],
        {
          replies: [
            ["whatWouldYouLike", "giveMeOneTea"],
            ["isItSpicy", "itIsVeryTasty"],
          ],
        },
      ),
      lesson(
        "food-review",
        "Food review",
        "CHECKPOINT",
        "Food words and restaurant phrases together.",
        [],
        {
          practice: [
            "rice",
            "tea",
            "water",
            "mango",
            "iAmHungry",
            "iAmThirsty",
            "iWantWater",
            "billPlease",
            "itIsVeryTasty",
          ],
          dialogue: "restaurant",
        },
      ),
    ],
  },
  {
    key: "numbers-time",
    title: "Numbers, time & dates",
    description: "Count, tell your age and the time, and talk about days.",
    stage: "FIRST_WORDS",
    lessons: [
      lesson("numbers-1-10", "Numbers 1–10", "VOCABULARY", "Count from one to ten.", [
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
      ]),
      lesson("numbers-11-20", "Numbers 11–20", "VOCABULARY", "Count from eleven to twenty.", [
        "eleven",
        "twelve",
        "thirteen",
        "fourteen",
        "fifteen",
        "sixteen",
        "seventeen",
        "eighteen",
        "nineteen",
        "twenty",
      ]),
      lesson(
        "big-numbers",
        "Tens & big numbers",
        "VOCABULARY",
        "Thirty, forty, fifty, a hundred and a thousand.",
        ["thirty", "forty", "fifty", "hundred", "thousand", "howMany"],
      ),
      lesson(
        "age-phone",
        "Age & phone numbers",
        "PHRASES",
        "Ask and say how old someone is, and ask for a phone number.",
        [
          "age",
          "year",
          "howOldAreYou",
          "iAmTwentyYearsOld",
          "phoneNumber",
          "whatIsYourPhoneNumber",
        ],
        { replies: [["howOldAreYou", "iAmTwentyYearsOld"]] },
      ),
      lesson(
        "time",
        "Time of day",
        "PHRASES",
        "Today, tomorrow, morning, night — and what time it is.",
        [
          "time",
          "now",
          "today",
          "tomorrow",
          "yesterday",
          "morning",
          "afternoon",
          "evening",
          "night",
          "whatTimeIsIt",
          "itIsFiveOClock",
        ],
        { replies: [["whatTimeIsIt", "itIsFiveOClock"]] },
      ),
      lesson(
        "days",
        "Days of the week",
        "VOCABULARY",
        "The seven days, and weeks and months.",
        [
          "monday",
          "tuesday",
          "wednesday",
          "thursday",
          "friday",
          "saturday",
          "sunday",
          "day",
          "week",
          "month",
          "whatDayIsToday",
          "todayIsMonday",
        ],
        { replies: [["whatDayIsToday", "todayIsMonday"]] },
      ),
      lesson(
        "numbers-review",
        "Numbers & time review",
        "CHECKPOINT",
        "Numbers, time and days together.",
        [],
        {
          practice: [
            "three",
            "seven",
            "twelve",
            "twenty",
            "hundred",
            "today",
            "tomorrow",
            "whatTimeIsIt",
            "howOldAreYou",
            "sunday",
          ],
        },
      ),
    ],
  },
  {
    key: "daily-life",
    title: "Daily life",
    description: "Everyday verbs and sentences about what you are doing.",
    stage: "SENTENCE_BUILDING",
    lessons: [
      lesson("routine-verbs", "Morning & evening", "VOCABULARY", "Verbs for your daily routine.", [
        "wakeUp",
        "sleep",
        "bathe",
        "cook",
        "wash",
        "wear",
      ]),
      lesson(
        "activity-verbs",
        "Study, work & play",
        "VOCABULARY",
        "Verbs for what you do during the day.",
        ["study", "work", "read", "write", "play", "listen", "speak"],
      ),
      lesson("movement-verbs", "Sit, stand & wait", "VOCABULARY", "Verbs for moving around.", [
        "sit",
        "stand",
        "walk",
        "run",
        "wait",
        "open",
        "close",
      ]),
      lesson(
        "what-are-you-doing",
        "What are you doing?",
        "PHRASES",
        "Say what you are doing right now.",
        [
          "whatAreYouDoing",
          "iAmStudying",
          "iAmEating",
          "iAmDrinkingWater",
          "iAmSleeping",
          "iAmWorking",
          "iAmComing",
          "iAmGoing",
        ],
        { replies: [["whatAreYouDoing", "iAmStudying"]] },
      ),
      lesson("my-day", "My day", "PHRASES", "Describe your daily routine.", [
        "everyDay",
        "iAmGoingHome",
        "iAmGoingToCollege",
        "iWakeUpAtSix",
        "iGoToCollegeEveryDay",
        "iEatLunchAtOne",
        "iSleepAtTen",
      ]),
      lesson(
        "daily-life-review",
        "Daily life review",
        "CHECKPOINT",
        "Talk about your day from morning to night.",
        [],
        {
          practice: [
            "wakeUp",
            "study",
            "work",
            "whatAreYouDoing",
            "iAmStudying",
            "iAmGoingHome",
            "iWakeUpAtSix",
            "iSleepAtTen",
          ],
          dialogue: "dailyRoutine",
        },
      ),
    ],
  },
  {
    key: "places",
    title: "Places & directions",
    description: "Places in town, where things are and how to get there.",
    stage: "SENTENCE_BUILDING",
    lessons: [
      lesson("places-1", "Places in town", "VOCABULARY", "Places you go to every day.", [
        "school",
        "college",
        "office",
        "shop",
        "market",
        "restaurant",
      ]),
      lesson("places-2", "More places", "VOCABULARY", "Places you may need to find.", [
        "hospital",
        "station",
        "bank",
        "temple",
        "bathroom",
        "road",
      ]),
      lesson(
        "position-words",
        "Near, far, left & right",
        "VOCABULARY",
        "Words for where things are.",
        ["near", "far", "left", "right", "straight", "inFront", "behind", "inside", "outside"],
      ),
      lesson(
        "asking-directions",
        "Asking for directions",
        "PHRASES",
        "Ask where a place is and understand the answer.",
        [
          "where",
          "whereIsTheBathroom",
          "whereIsTheStation",
          "goStraight",
          "turnLeft",
          "turnRight",
          "itIsNear",
          "itIsFar",
          "howFarIsIt",
        ],
        { replies: [["howFarIsIt", "itIsNear"]] },
      ),
      lesson(
        "where-are-you-going",
        "Where are you going?",
        "PHRASES",
        "Ask and say where people are and where they are going.",
        [
          "whereAreYouGoing",
          "iAmGoingToTheMarket",
          "whereAreYou",
          "iAmAtHome",
          "comeHere",
          "waitHere",
        ],
        {
          replies: [
            ["whereAreYouGoing", "iAmGoingToTheMarket"],
            ["whereAreYou", "iAmAtHome"],
          ],
        },
      ),
      lesson("places-review", "Places review", "CHECKPOINT", "Find your way around town.", [], {
        practice: [
          "hospital",
          "market",
          "left",
          "right",
          "near",
          "whereIsTheBathroom",
          "goStraight",
          "whereAreYouGoing",
        ],
        dialogue: "directions",
      }),
    ],
  },
  {
    key: "shopping",
    title: "Shopping & money",
    description: "Prices, colours, clothes and how to buy (and bargain) politely.",
    stage: "EVERYDAY_PHRASES",
    lessons: [
      lesson(
        "money-words",
        "Money & prices",
        "VOCABULARY",
        "Words for buying and selling.",
        ["rupee", "price", "buy", "sell", "expensive", "cheap", "howMuch"],
        { practice: ["money", "shop"] },
      ),
      lesson("colours", "Colours", "VOCABULARY", "Six colours you will use all the time.", [
        "colour",
        "red",
        "blue",
        "green",
        "yellow",
        "white",
        "black",
      ]),
      lesson("clothes", "Clothes", "VOCABULARY", "Things to wear.", [
        "clothes",
        "shirt",
        "trousers",
        "saree",
        "shoes",
        "slippers",
      ]),
      lesson(
        "at-the-shop",
        "At the shop",
        "PHRASES",
        "Ask prices, ask for what you need and bargain politely.",
        [
          "howMuchIsThis",
          "thisIsTooExpensive",
          "reduceThePrice",
          "doYouHaveMangoes",
          "iNeedABag",
          "giveMeThisOne",
          "iWillTakeIt",
          "showMeThatOne",
          "doYouHaveARedOne",
        ],
        { replies: [["thisIsTooExpensive", "reduceThePrice"]] },
      ),
      lesson("shopping-review", "Shopping review", "CHECKPOINT", "A complete shopping trip.", [], {
        practice: [
          "howMuchIsThis",
          "thisIsTooExpensive",
          "red",
          "shirt",
          "rupee",
          "expensive",
          "iWillTakeIt",
        ],
        dialogue: "shopping",
      }),
    ],
  },
  {
    key: "travel",
    title: "Travel & transport",
    description: "Buses, trains and autos — tickets, times and getting where you want to go.",
    stage: "EVERYDAY_PHRASES",
    lessons: [
      lesson("vehicles", "Getting around", "VOCABULARY", "Ways to travel.", [
        "bus",
        "train",
        "autoRickshaw",
        "taxi",
        "car",
        "bike",
      ]),
      lesson("travel-words", "Tickets & stations", "VOCABULARY", "Words you need at a station.", [
        "ticket",
        "platform",
        "busStop",
        "airport",
        "luggage",
        "journey",
      ]),
      lesson("when-how-long", "When & how long?", "PHRASES", "Ask about time when you travel.", [
        "when",
        "howLong",
        "late",
        "early",
        "quickly",
        "slowly",
        "whenDoesTheBusCome",
        "howLongDoesItTake",
        "theTrainIsLate",
      ]),
      lesson("travel-phrases", "Travel phrases", "PHRASES", "Buy tickets and talk to drivers.", [
        "oneTicketPlease",
        "whichPlatform",
        "stopHerePlease",
        "goSlowlyPlease",
        "howMuchToStation",
        "iAmLost",
        "doesThisBusGoToStation",
      ]),
      lesson("travel-review", "Travel review", "CHECKPOINT", "A whole bus journey.", [], {
        practice: [
          "bus",
          "ticket",
          "whenDoesTheBusCome",
          "stopHerePlease",
          "iAmLost",
          "howMuchToStation",
        ],
        dialogue: "travel",
      }),
    ],
  },
  {
    key: "conversations",
    title: "Everyday conversations",
    description: "Short real-life conversations that put everything together.",
    stage: "CONVERSATION",
    lessons: [
      lesson(
        "conv-meeting",
        "Meeting someone new",
        "PHRASES",
        "A first conversation with someone new.",
        [],
        {
          practice: ["hello", "whatIsYourName", "myNameIs", "whereAreYouFrom", "niceToMeetYou"],
          dialogue: "meetingSomeone",
        },
      ),
      lesson(
        "conv-friend",
        "Meeting a friend",
        "PHRASES",
        "Catch up with a friend.",
        ["whatsNew", "longTimeNoSee", "haveYouEaten", "yesIAte"],
        { dialogue: "meetingFriend", replies: [["haveYouEaten", "yesIAte"]] },
      ),
      lesson(
        "conv-college",
        "At college",
        "PHRASES",
        "Find your way on your first day.",
        ["whereIsTheClass", "whenIsTheExam", "canIComeIn", "isThisSeatFree"],
        { dialogue: "college" },
      ),
      lesson(
        "conv-phone",
        "On the phone",
        "PHRASES",
        "Make and answer a phone call.",
        ["hello_onPhone", "whoIsSpeaking", "callYouLater", "canYouHearMe", "justAMinute"],
        { dialogue: "phoneCall", replies: [["whoIsSpeaking", "myNameIs"]] },
      ),
      lesson(
        "conv-help",
        "Asking for help",
        "PHRASES",
        "Ask a stranger for help.",
        ["whatIsTheNameOfThisPlace", "ofCourse"],
        {
          practice: ["excuseMe", "iAmLost", "speakSlowly", "iDontUnderstand"],
          dialogue: "askingForHelp",
        },
      ),
      lesson(
        "conv-review",
        "Conversation review",
        "CHECKPOINT",
        "Pick the right reply in everyday situations.",
        [],
        {
          practice: [
            "howAreYou",
            "haveYouEaten",
            "whoIsSpeaking",
            "canIComeIn",
            "justAMinute",
            "ofCourse",
          ],
          replies: [
            ["howAreYou", "iAmFine"],
            ["haveYouEaten", "yesIAte"],
            ["canIComeIn", "ofCourse"],
            ["thankYou", "youreWelcome"],
          ],
        },
      ),
    ],
  },
  {
    key: "grammar",
    title: "Grammar & sentence building",
    description: "Pronouns, word order, tenses, questions, negatives and politeness.",
    stage: "GRAMMAR",
    lessons: [
      lesson(
        "pronouns",
        "I, you, he, she…",
        "VOCABULARY",
        "Personal pronouns. Most Indian languages have a casual and a polite “you”.",
        ["youCasual", "he", "she", "we", "they", "itPronoun"],
        { practice: ["iPronoun", "youFormal"] },
      ),
      lesson(
        "word-order",
        "Word order & the present",
        "PHRASES",
        "Indian languages usually put the verb at the end: “I rice eat”.",
        [
          "iEatRice",
          "sheDrinksTea",
          "weGoToCollege",
          "heReadsABook",
          "theyLiveInIndia",
          "myMotherCooksFood",
          "iSpeakEnglish",
        ],
      ),
      lesson("past-future", "Past & future", "PHRASES", "Talk about yesterday and tomorrow.", [
        "iAteRice",
        "iWillEatRice",
        "iWentToTheMarketYesterday",
        "iWillGoTomorrow",
        "sheCameYesterday",
        "weWillComeTomorrow",
      ]),
      lesson(
        "questions-negatives",
        "Questions & negatives",
        "PHRASES",
        "Ask yes/no questions and say “not”.",
        [
          "why",
          "how",
          "which",
          "doYouEatMeat",
          "iDontKnow",
          "isThisYourBook",
          "thisIsNotMyBook",
          "whyAreYouLate",
          "howDoYouGoToCollege",
        ],
        { replies: [["doYouEatMeat", "iDontEatMeat"]] },
      ),
      lesson(
        "possession",
        "My, your & small words",
        "PHRASES",
        "Possession and the small words for in, on, with and from.",
        [
          "inPostposition",
          "onPostposition",
          "withPostposition",
          "fromPostposition",
          "table",
          "thisIsMyBook",
          "hisNameIsRavi",
          "theBookIsOnTheTable",
          "iGoWithMyFriend",
          "sheIsComingFromHome",
        ],
      ),
      lesson(
        "polite-casual",
        "Polite & casual",
        "PHRASES",
        "The same request, said to a friend and said politely.",
        ["comeCasual", "comePolite", "sitCasual", "sitPolite", "eatPolite", "howAreYouCasual"],
      ),
      lesson(
        "grammar-review",
        "Grammar review",
        "CHECKPOINT",
        "Build sentences with everything you know.",
        [],
        {
          practice: [
            "iEatRice",
            "iAteRice",
            "iWillEatRice",
            "thisIsNotMyBook",
            "doYouEatMeat",
            "comePolite",
            "she",
            "they",
          ],
        },
      ),
    ],
  },
  {
    key: "feelings",
    title: "Feelings, health & relationships",
    description: "Say how you feel, talk about health and tell people you care.",
    stage: "SPEAKING",
    lessons: [
      lesson("feelings", "How do you feel?", "PHRASES", "Words and sentences for feelings.", [
        "happy",
        "sad",
        "angry",
        "tired",
        "scared",
        "worried",
        "iAmHappy",
        "iAmSad",
        "iAmTired",
      ]),
      lesson(
        "feelings-2",
        "I'm okay, don't worry",
        "PHRASES",
        "Comfort someone and say how you are.",
        ["iAmAngry", "iAmOkay", "iAmNotFeelingWell", "dontWorry", "iAmScared"],
        { replies: [["iAmNotFeelingWell", "dontWorry"]] },
      ),
      lesson("body", "The body", "VOCABULARY", "Parts of the body.", [
        "head",
        "hand",
        "leg",
        "eye",
        "ear",
        "mouth",
        "stomach",
        "tooth",
      ]),
      lesson("health", "At the doctor", "PHRASES", "Explain what is wrong and ask for help.", [
        "fever",
        "medicine",
        "iHaveAFever",
        "iHaveAHeadache",
        "myStomachHurts",
        "iNeedADoctor",
        "callADoctor",
        "takeThisMedicine",
      ]),
      lesson(
        "love-friendship",
        "Love & friendship",
        "PHRASES",
        "Tell people you love them, like them or miss them.",
        [
          "iLoveYou",
          "iLikeYou",
          "iMissYou",
          "iLoveMyFamily",
          "youAreMyFriend",
          "youAreMyBestFriend",
          "iLikeThis",
          "iDontLikeThis",
          "takeCare",
        ],
      ),
      lesson(
        "feelings-review",
        "Feelings review",
        "CHECKPOINT",
        "Feelings, health and kind words.",
        [],
        {
          practice: [
            "iAmHappy",
            "iAmTired",
            "iAmNotFeelingWell",
            "iHaveAFever",
            "iLoveYou",
            "iMissYou",
            "head",
            "stomach",
          ],
        },
      ),
    ],
  },
  {
    key: "practical",
    title: "Practical communication",
    description: "Weather, college and work, hobbies, plans and asking for help.",
    stage: "CONVERSATION",
    lessons: [
      lesson("weather", "Weather", "PHRASES", "Talk about the weather.", [
        "weather",
        "hot",
        "cold",
        "rain",
        "sun",
        "wind",
        "itIsHotToday",
        "itIsRaining",
        "itIsColdToday",
      ]),
      lesson("college-work", "College & work", "PHRASES", "Classes, exams and jobs.", [
        "classroom",
        "exam",
        "homework",
        "job",
        "holiday",
        "iHaveAnExamTomorrow",
        "todayIsAHoliday",
        "iWorkInAnOffice",
      ]),
      lesson(
        "hobbies",
        "Hobbies & likes",
        "PHRASES",
        "Talk about what you like doing.",
        [
          "music",
          "movie",
          "song",
          "cricket",
          "dance",
          "iLikeMusic",
          "doYouLikeCricket",
          "iLikeWatchingMovies",
          "whatIsYourHobby",
        ],
        { replies: [["whatIsYourHobby", "iLikeMusic"]] },
      ),
      lesson(
        "plans",
        "Plans & invitations",
        "PHRASES",
        "Invite people and accept or say no politely.",
        [
          "letsGo",
          "comeToMyHouse",
          "areYouFreeTomorrow",
          "yesIWillCome",
          "sorryICantCome",
          "seeYouTomorrow",
        ],
        {
          replies: [
            ["areYouFreeTomorrow", "yesIWillCome"],
            ["comeToMyHouse", "sorryICantCome"],
          ],
        },
      ),
      lesson(
        "requests-help",
        "Requests & help",
        "PHRASES",
        "Ask for help and make polite requests.",
        [
          "canYouHelpMe",
          "iNeedHelp",
          "pleaseHelpMe",
          "pleaseWait",
          "pleaseTellMe",
          "pleaseShowMe",
          "callMe",
          "help",
          "itsOkay",
        ],
        { replies: [["canYouHelpMe", "ofCourse"]] },
      ),
      lesson(
        "final-review",
        "Final review",
        "CHECKPOINT",
        "A last mix of everything in the course.",
        [],
        {
          practice: [
            "myNameIs",
            "iAmHungry",
            "whereIsTheBathroom",
            "howMuchIsThis",
            "iLoveYou",
            "canYouHelpMe",
            "iDontUnderstand",
            "itIsRaining",
            "letsGo",
            "iWillGoTomorrow",
          ],
        },
      ),
    ],
  },
];

/** Placement test: 3 questions from each of these units (by unit number). */
export const PLACEMENT_UNITS = [1, 2, 4, 5, 7, 9];
