// Writes the course dialogues into the AI tutor's knowledge base:
//   npm run content:dialogues -w backend   →   backend/knowledge-base/<code>/dialogues.md
//
// The dialogues live in content/languages/<code>.ts (they are also used by the lessons'
// "what comes next?" exercises). This keeps the knowledge-base copy identical. Re-run it after
// editing a dialogue, then `npm run rag:index -w backend`.
import { writeFile } from "node:fs/promises";
import { DIALOGUES, type DialogueKey } from "./curriculum.ts";
import { SEED_LANGUAGES } from "./index.ts";

/** Knowledge-base topic of each dialogue (the role-play scenarios search by these topics). */
const DIALOGUE_TOPICS: Record<DialogueKey, string> = {
  meetingSomeone: "introductions",
  meetingFriend: "everyday-conversation",
  restaurant: "restaurant",
  shopping: "shopping",
  directions: "directions",
  college: "college",
  phoneCall: "everyday-conversation",
  askingForHelp: "requests",
  travel: "travel",
  dailyRoutine: "daily-routine",
};

const knowledgeBase = new URL("../../knowledge-base/", import.meta.url);

for (const language of SEED_LANGUAGES) {
  const lines = [
    "---",
    `language: ${language.code}`,
    `title: ${language.name} beginner dialogues`,
    "type: example",
    "level: beginner",
    "skill: conversation",
    "topic: everyday-conversation",
    "source: Vachan course content",
    "---",
    "",
    `<!-- Generated by \`npm run content:dialogues -w backend\` from prisma/content/languages/${language.code}.ts — edit the dialogue there, not here. -->`,
    "",
    `# ${language.name} beginner dialogues`,
    "",
  ];
  for (const key of Object.keys(DIALOGUES) as DialogueKey[]) {
    const dialogue = language.content.dialogues[key];
    lines.push(`## Dialogue: ${DIALOGUES[key].title} in ${language.name}`, "");
    lines.push(`<!-- topic: ${DIALOGUE_TOPICS[key]} -->`, "");
    lines.push(
      `A short ${language.name} conversation — ${DIALOGUES[key].title.toLowerCase()}. ${dialogue.context}`,
      "",
    );
    for (const line of dialogue.lines) {
      lines.push(`- **${line.speaker}:** ${line.script} (${line.roman}) — "${line.meaning}"`);
    }
    lines.push("");
  }
  const path = new URL(`${language.code}/dialogues.md`, knowledgeBase);
  await writeFile(path, lines.join("\n"));
  console.log(`✓ ${language.code}/dialogues.md (${Object.keys(DIALOGUES).length} dialogues)`);
}
